#!/bin/sh

DB_USER="synolibrary"
DB_NAME="synolibrary"

PSQL_BIN="/usr/bin/psql"

PYTHON_MODULE_PATH="/usr/local/lib/python2.7/site-packages"

sudo -u $DB_USER $PSQL_BIN -U $DB_USER -f $SYNOPKG_PKGDEST/scripts/sql/create.sql $DB_NAME
sudo -u $DB_USER $PSQL_BIN -U $DB_USER -f $SYNOPKG_PKGDEST/scripts/sql/insert.sql $DB_NAME

ln -svf $SYNOPKG_PKGDEST/usr/lib/python2.7/site-packages/configparser-3.5.0-py2.7-nspkg.pth ${PYTHON_MODULE_PATH}
ln -svf $SYNOPKG_PKGDEST/usr/lib/python2.7/site-packages/configparser.py ${PYTHON_MODULE_PATH}
ln -svf $SYNOPKG_PKGDEST/usr/lib/python2.7/site-packages/backports ${PYTHON_MODULE_PATH}

exit 0
